server:
    port: 9411
eureka:
    client:
      service-url:
         defaultZone: http://user:123456@localhost:8762/eureka/
spring:
  application:
    name: zipkin
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3308/zipkin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&useOldAliasMetadataBehavior=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:/zipkin.sql
    initialize: true
    continue-on-error: true